#!/usr/bin/env bash
# Configure your Nginx server that /redirect_me is redirecting to another page

sudo apt-get update
sudo apt-get install -y nginx

# code to redirect to a specific endpoint (e.g redirect /redirect_me to https://www.youtube.com/watch?v=QH2-TGUlwu4)
echo "Hello World!" | sudo tee /var/www/html/index.html
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# code to create an error page and redirect for 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# restart the server
sudo service nginx restart
