#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.

CONFIG_SETTINGS="
frontend myfrontend
    bind *:80
    mode http
    default_backend web_servers
backend web_servers
   balance roundrobin
   server 4323-web-01 52.23.231.242:80 check
   server 4323-web-02 34.229.134.248:80 check
"

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
printf "%s" "$CONFIG_SETTINGS" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
